Homework_22_1/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('product.urls', 'product'))),
    path('/materials/', include(('materials.urls', 'materials')))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

materials/urls.py
from django.urls import path

from materials.views import *

app_name = 'materials'

urlpatterns = [
    path('', MaterialsListView.as_view(), name='material_list'),
    path('create/', MaterialsCreateView.as_view(), name='material_create'),
    path('view/<int:pk>/', MaterialsDetailView.as_view(), name='material_detail'),
    path('edit/<int:pk>/', MaterialsUpdateView.as_view(), name='material_edit'),
    path('delete/<int:pk>/', MaterialsDeleteView.as_view(), name='material_delete')
]

product/urls.py
from django.urls import path

from product.views import *

app_name = 'product'

urlpatterns = [
    path('', ProductListView.as_view(), name='index'),
    path('view/<int:pk>/', ProductDetailView.as_view(), name='view'),
    path('contacts/', contacts, name='contacts'),
    path('create/', ProductCreateView.as_view(), name='create'),
    path('edit/<int:pk>/', ProductUpdateView.as_view(), name='edit'),
    path('delete/<int:pk>/', ProductDeleteView.as_view(), name='delete')
]

materials/models.py
from django.db import models


class Material(models.Model):
    title = models.CharField(max_length=100, verbose_name='Заголовок')
    body = models.TextField(verbose_name='Содержимое')
    image = models.ImageField(upload_to='materials/', verbose_name='Изображение', null=True, blank=True)
    slug = models.CharField(max_length=150)
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')
    is_active = models.BooleanField(default=True, verbose_name='Статус')
    views_count = models.IntegerField(default=0, verbose_name='Просмотры')

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Материал'
        verbose_name_plural = 'Материалы'

materials/views.py
from django.shortcuts import render
from django.urls import reverse_lazy, reverse
from django.views.generic import ListView, CreateView, DetailView, UpdateView, DeleteView
from pytils.translit import slugify

from materials.models import Material


class MaterialsListView(ListView):
    model = Material


class MaterialsDetailView(DetailView):
    model = Material

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        self.object.views_count += 1
        self.object.save()
        return self.object


class MaterialsCreateView(CreateView):
    model = Material
    fields = ('title', 'body', 'image')
    success_url = reverse_lazy('materials:material_list')

    def form_valid(self, form):
        if form.is_valid():
            new_material = form.save()
            new_material.slug = slugify(new_material.title)
            new_material.save()

        return super().form_valid(form)


class MaterialsUpdateView(UpdateView):
    model = Material
    fields = ('title', 'body', 'image',)

    def form_valid(self, form):
        if form.is_valid():
            new_material = form.save()
            new_material.slug = slugify(new_material.title)
            new_material.save()

        return super().form_valid(form)

    def get_success_url(self):
        return reverse('materials:material_detail', args=(self.kwargs.get('pk'),))


class MaterialsDeleteView(DeleteView):
    model = Material
    success_url = reverse_lazy('materials:material_list')

materials/templates/materials/material_confirm_delete.html
{% extends 'product/base.html' %}

{% block content %}
    <section class="py-2 text-center container">
        <div class="row py-lg-5">
            <div class="col-lg-6 col-md-8 mx-auto">
                <h4>Удаление материала</h4>
            </div>
        </div>
    </section>
    <div class="album py-5 bg-body-tertiary">
        <div class="container">
            <div class="row">
                <div class="col-6">
                    <div class="card">
                        <div class="card">
                            <form method="post">
                                {% csrf_token %}
                                <div class="card-header">
                                    <h6>Хотите удалить материал "{{ object.title }}"</h6>
                                </div>
                                <div class="card-body">
                                    <button type="submit" class="btn btn-outline-danger">Подтвердить</button>
                                    <a href="{% url 'materials:material_list' %}" class="btn btn-outline-warning">
                                        Отменить</a>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

materials/templates/materials/material_detail.html
{% extends 'product/base.html' %}
{% load tags %}
{% block content %}
    <div class="album py-5 bg-body-tertiary">
        <div class="container">
            <div class="row">
                <div class="col-8">
                    <div class="card">
                        <div class="card-header">
                            <h5>Материал "{{ object.title }}" ({{ object.slug }})</h5>
                        </div>
                        <div class="card-body">
                            <p> Описание: {{ object.body }}</p>
                        </div>
                        <div class="card-footer">
                            <p class="float-right">
                                <a href="{% url 'materials:material_list' %}"
                                   class="btn btn-outline-secondary">Вернуться</a>
                            </p>
                            <p class="float-right">
                                Просмотры: {{ object.views_count }}
                            </p>
                        </div>
                    </div>
                </div>
                <div class="col-4">
                    <div class="card-body d-flex flex-column py-4">
                        {% if object.image %}
                            <img src="{% media_path material.image %}" alt="No photo" class="mx-auto"
                                 style="height: 200px; width: 150px;"/>
                        {% else %}
                            <p class="text-center py-5">
                                Здесь скоро <br>
                                появится <br>
                                изображение
                            </p>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

materials/templates/materials/material_form.html
{% extends 'product/base.html' %}
{% load crispy_forms_tags %}
{% load crispy_forms_filters %}

{% block content %}
    <div class="album py-5 bg-body-tertiary">
        <div class="container">
            <div class="row">
                <div class="col-6">
                    <div class="card">
                        <div class="card-body">
                            <form method="post">
                                {% csrf_token %}
                                {{ form|crispy }}
                                <button type="submit" class="btn btn-success">
                                    {% if object %}
                                        Сохранить
                                    {% else %}
                                        Создать
                                    {% endif %}
                                </button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

materials/templates/materials/material_list.html
{% extends 'product/base.html' %}

{% block content %}
    <section class="py-2 text-center container">
        <div class="row py-lg-5">
            <div class="col-lg-6 col-md-8 mx-auto">
                <a class="btn btn-outline-secondary" href="{% url 'materials:material_create' %}">Добавить
                    материал</a>
            </div>
        </div>
    </section>


    <div class="album py-5 bg-body-tertiary">
        <div class="container">
            <div class="row">
                {% if object_list %}
                    {% for object in object_list %}
                        <div class="col-4 d-flex flex-column align-items-center">
                            <div class="card">
                                <div class="card-header">
                                    {{ object.title }}
                                </div>
                                <div class="card-body">
                                    <div class="d-flex justify-content-between align-items-center">
                                        <div class="btn-group">
                                            <a href="{% url 'materials:material_detail' object.pk %}" type="button"
                                               class="btn btn-sm btn-outline-secondary">Просмотр</a>
                                            <a href="{% url 'materials:material_edit' object.pk %}" type="button"
                                               class="btn btn-sm btn-outline-secondary">Редактирование</a>
                                            <a href="{% url 'materials:material_delete' object.pk %}" type="button"
                                               class="btn btn-sm btn-outline-danger">Удалить</a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    {% endfor %}
                {% else %}
                    Ничего не найдено
                {% endif %}
            </div>
        </div>
    </div>


{% endblock %}