Homework_22_1/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('product.urls', 'product'))),
    path('/materials/', include(('materials.urls', 'materials')))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

materials/urls.py
from django.urls import path

from materials.views import *

app_name = 'materials'

urlpatterns = [
    path('', MaterialsListView.as_view(), name='material_list'),
    path('create/', MaterialsCreateView.as_view(), name='material_create'),
    path('view/<int:pk>/', MaterialsDetailView.as_view(), name='material_detail'),
    path('edit/<int:pk>/', MaterialsUpdateView.as_view(), name='material_edit'),
    path('delete/<int:pk>/', MaterialsDeleteView.as_view(), name='material_delete')
]

product/urls.py
from django.urls import path

from product.views import *

app_name = 'product'

urlpatterns = [
    path('', ProductListView.as_view(), name='index'),
    path('view/<int:pk>/', ProductDetailView.as_view(), name='view'),
    path('contacts/', contacts, name='contacts'),
    path('create/', ProductCreateView.as_view(), name='create'),
    path('edit/<int:pk>/', ProductUpdateView.as_view(), name='edit'),
    path('delete/<int:pk>/', ProductDeleteView.as_view(), name='delete')
]

product/models.py
from django.db import models

NULLABLE = {
    'null': True,
    'blank': True
}


class Product(models.Model):
    title = models.CharField(max_length=200, verbose_name="Название")
    description = models.TextField(verbose_name="Описание")
    image = models.ImageField(upload_to="images/", verbose_name="Изображение")
    price = models.IntegerField(verbose_name="Стоимость")
    created_at = models.DateTimeField(auto_now_add=True, verbose_name="Дата создания")
    updated_at = models.DateTimeField(
        auto_now=True, verbose_name="Дата последнего изменения"
    )
    category = models.ForeignKey(
        "Category", on_delete=models.CASCADE, verbose_name="Категория"
    )

    active = models.BooleanField(default=True, verbose_name="Наличие")

    def __str__(self):
        return f"{self.title}"

    class Meta:
        verbose_name = "Продукт"
        verbose_name_plural = "Продукты"


class Category(models.Model):
    product_name = models.CharField(max_length=150, verbose_name="Категория")
    description = models.TextField(verbose_name="Описание")

    def __str__(self):
        return self.product_name

    class Meta:
        verbose_name = "Категория"
        verbose_name_plural = "Категории"


class Version(models.Model):
    product = models.ForeignKey(
        Product,
        on_delete=models.CASCADE,
        verbose_name="продукт",
        related_name="versions",
    )
    version_number = models.FloatField(verbose_name="версия продукта")
    version_name = models.CharField(max_length=50, verbose_name="название версии")
    active = models.BooleanField(default=False, verbose_name="активная")

    def __str__(self):
        return f"{self.version_name}"

    class Meta:
        verbose_name = "версия"
        verbose_name_plural = "версии"

product/forms.py
from django import forms
from django.forms import CheckboxInput, ValidationError

from product.models import *

FORBIDDEN_WORDS = [
    "казино",
    "криптовалюта",
    "крипта",
    "биржа",
    "дешево",
    "бесплатно",
    "обман",
    "полиция",
    "радар",
]


def validate_no_forbidden_words(value):
    for word in FORBIDDEN_WORDS:
        if word.lower() in value.lower():
            raise ValidationError(f"Слово '{word}' не допускается.")


class ContactForm(forms.Form):
    first_name = forms.CharField(label="Имя", max_length=20)
    email = forms.EmailField(label="Email")
    question = forms.CharField(
        label="Введите Ваш вопрос",
        max_length=200,
        help_text="не более 200 символов",
        widget=forms.Textarea(attrs={"style": "height: 65px;"}),
    )


class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = ["title", "description", "image", "price", "active", "category"]
        widgets = {"active": CheckboxInput()}
        labels = {
            "title": "Название",
            "description": "Описание",
            "image": "Изображение",
            "price": "Стоимость",
            "active": "Активная",
            "category": "Категория",
        }

        title = forms.CharField(
            label="Название", max_length=50, validators=[validate_no_forbidden_words]
        )
        description = forms.CharField(
            label="Описание",
            max_length=600,
            help_text="не более 600 символов",
            validators=[validate_no_forbidden_words],
        )


class VersionForm(forms.ModelForm):
    class Meta:
        model = Version
        fields = "__all__"

    def clean(self):
        cleaned_data = super().clean()
        counter = 0

        try:

            existing_instance = self.instance.product.versions.filter(active=True)
            for active_version in existing_instance:
                print(active_version)
                if active_version:
                    if self.instance.pk is not None:
                        self.instance.active = cleaned_data.get('active', False)
                        counter += 1

            if counter > 1:
                raise forms.ValidationError('Активная версия должна быть только одна')


        except Version.DoesNotExist:
            pass

        return cleaned_data

    def save(self, commit=True):
        instance = super().save(commit=commit)
        if commit and instance.active:
            existing_active_versions = instance.product.versions.filter(active=True).exclude(pk=instance.pk)
            for active_version in existing_active_versions:
                active_version.active = False
                active_version.save()
        return instance

product/views.py
from django.forms import inlineformset_factory
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView

from product.forms import *
from product.models import *


class ProductListView(ListView):
    model = Product

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        products = context['product_list']

        active_versions_per_product = {product.id: Version.objects.filter(product=product, active=True).first() for
                                       product in products}
        context['active_versions'] = active_versions_per_product

        return context


class ProductDetailView(DetailView):
    model = Product


def contacts(request):
    if request.method == 'POST':
        form = ContactForm(request.POST)
        if form.is_valid():
            first_name = request.POST.get('first_name')
            email = request.POST.get('email')
            question = request.POST.get('question')
            print(f'Имя: {first_name}, email: ({email}), Вопрос {question}')
            return redirect('product:contacts')
    else:
        form = ContactForm()
    return render(request, 'product/contacts.html', {'form': form})


class ProductCreateView(CreateView):
    model = Product
    form_class = ProductForm
    template_name = 'product/product_form.html'
    success_url = reverse_lazy('product:index')

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        VersionFormset = inlineformset_factory(Product, Version, form=VersionForm, extra=1)
        if self.request.method == 'POST':
            context_data['formset'] = VersionFormset(self.request.POST)
        else:
            context_data['formset'] = VersionFormset()
        return context_data

    def form_valid(self, form):
        self.object = form.save()
        formset = inlineformset_factory(Product, Version, form=VersionForm)(self.request.POST, instance=self.object)
        if formset.is_valid():
            formset.save()
            return super().form_valid(form)
        else:
            return self.form_invalid(form)


class ProductUpdateView(UpdateView):
    model = Product
    form_class = ProductForm
    template_name = 'product/product_form.html'

    def get_success_url(self):
        return reverse_lazy('product:view', args=[self.object.pk])

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        FormSet = inlineformset_factory(Product, Version, form=VersionForm, extra=1)
        if self.request.method == 'POST':
            context_data['formset'] = FormSet(self.request.POST, instance=self.object)
        else:
            context_data['formset'] = FormSet(instance=self.object)
        return context_data

    def form_valid(self, form):
        self.object = form.save()
        formset = inlineformset_factory(Product, Version, form=VersionForm)(self.request.POST, instance=self.object)
        if formset.is_valid():
            formset.save()
            return super().form_valid(form)
        else:
            return self.form_invalid(form)


class ProductDeleteView(DeleteView):
    model = Product
    success_url = reverse_lazy('product:index')

product/templates/product/base.html
{% load static %}
<!doctype html>
<html lang="en" data-bs-theme="auto">
<head>
    <script src="{% static 'js/color-modes.js' %}"></script>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.118.2">
    <title>Album example · Bootstrap v5.3</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/5.3/examples/album/">


    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@docsearch/css@3">

    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet"
          integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">

    {#    <!-- Favicons -->#}
    {#    <link rel="apple-touch-icon" href="/docs/5.3/assets/img/favicons/apple-touch-icon.png" sizes="180x180">#}
    {#    <link rel="icon" href="/docs/5.3/assets/img/favicons/favicon-32x32.png" sizes="32x32" type="image/png">#}
    {#    <link rel="icon" href="/docs/5.3/assets/img/favicons/favicon-16x16.png" sizes="16x16" type="image/png">#}
    {#    <link rel="manifest" href="/docs/5.3/assets/img/favicons/manifest.json">#}
    {#    <link rel="mask-icon" href="/docs/5.3/assets/img/favicons/safari-pinned-tab.svg" color="#712cf9">#}
    {#    <link rel="icon" href="/docs/5.3/assets/img/favicons/favicon.ico">#}
    {#    <meta name="theme-color" content="#712cf9">#}


    <style>
        .bd-placeholder-img {
            font-size: 1.125rem;
            text-anchor: middle;
            -webkit-user-select: none;
            -moz-user-select: none;
            user-select: none;
        }

        @media (min-width: 768px) {
            .bd-placeholder-img-lg {
                font-size: 3.5rem;
            }
        }

        .b-example-divider {
            width: 100%;
            height: 3rem;
            background-color: rgba(0, 0, 0, .1);
            border: solid rgba(0, 0, 0, .15);
            border-width: 1px 0;
            box-shadow: inset 0 .5em 1.5em rgba(0, 0, 0, .1), inset 0 .125em .5em rgba(0, 0, 0, .15);
        }

        .b-example-vr {
            flex-shrink: 0;
            width: 1.5rem;
            height: 100vh;
        }

        .bi {
            vertical-align: -.125em;
            fill: currentColor;
        }

        .nav-scroller {
            position: relative;
            z-index: 2;
            height: 2.75rem;
            overflow-y: hidden;
        }

        .nav-scroller .nav {
            display: flex;
            flex-wrap: nowrap;
            padding-bottom: 1rem;
            margin-top: -1px;
            overflow-x: auto;
            text-align: center;
            white-space: nowrap;
            -webkit-overflow-scrolling: touch;
        }

        .btn-bd-primary {
            --bd-violet-bg: #712cf9;
            --bd-violet-rgb: 112.520718, 44.062154, 249.437846;

            --bs-btn-font-weight: 600;
            --bs-btn-color: var(--bs-white);
            --bs-btn-bg: var(--bd-violet-bg);
            --bs-btn-border-color: var(--bd-violet-bg);
            --bs-btn-hover-color: var(--bs-white);
            --bs-btn-hover-bg: #6528e0;
            --bs-btn-hover-border-color: #6528e0;
            --bs-btn-focus-shadow-rgb: var(--bd-violet-rgb);
            --bs-btn-active-color: var(--bs-btn-hover-color);
            --bs-btn-active-bg: #5a23c8;
            --bs-btn-active-border-color: #5a23c8;
        }

        .bd-mode-toggle {
            z-index: 1500;
        }

        .bd-mode-toggle .dropdown-menu .active .bi {
            display: block !important;
        }

        .list-unstyled a {
            text-decoration: none;
        }

        hr {
            border: none;
            height: 4px; /* Высота линии */
            background-color: black; /* Цвет линии */
        }

    </style>


</head>
<body>
<svg xmlns="http://www.w3.org/2000/svg" class="d-none">
    <symbol id="check2" viewBox="0 0 16 16">
        <path d="M13.854 3.646a.5.5 0 0 1 0 .708l-7 7a.5.5 0 0 1-.708 0l-3.5-3.5a.5.5 0 1 1 .708-.708L6.5 10.293l6.646-6.647a.5.5 0 0 1 .708 0z"/>
    </symbol>
    <symbol id="circle-half" viewBox="0 0 16 16">
        <path d="M8 15A7 7 0 1 0 8 1v14zm0 1A8 8 0 1 1 8 0a8 8 0 0 1 0 16z"/>
    </symbol>
    <symbol id="moon-stars-fill" viewBox="0 0 16 16">
        <path d="M6 .278a.768.768 0 0 1 .08.858 7.208 7.208 0 0 0-.878 3.46c0 4.021 3.278 7.277 7.318 7.277.527 0 1.04-.055 1.533-.16a.787.787 0 0 1 .81.316.733.733 0 0 1-.031.893A8.349 8.349 0 0 1 8.344 16C3.734 16 0 12.286 0 7.71 0 4.266 2.114 1.312 5.124.06A.752.752 0 0 1 6 .278z"/>
        <path d="M10.794 3.148a.217.217 0 0 1 .412 0l.387 1.162c.173.518.579.924 1.097 1.097l1.162.387a.217.217 0 0 1 0 .412l-1.162.387a1.734 1.734 0 0 0-1.097 1.097l-.387 1.162a.217.217 0 0 1-.412 0l-.387-1.162A1.734 1.734 0 0 0 9.31 6.593l-1.162-.387a.217.217 0 0 1 0-.412l1.162-.387a1.734 1.734 0 0 0 1.097-1.097l.387-1.162zM13.863.099a.145.145 0 0 1 .274 0l.258.774c.115.346.386.617.732.732l.774.258a.145.145 0 0 1 0 .274l-.774.258a1.156 1.156 0 0 0-.732.732l-.258.774a.145.145 0 0 1-.274 0l-.258-.774a1.156 1.156 0 0 0-.732-.732l-.774-.258a.145.145 0 0 1 0-.274l.774-.258c.346-.115.617-.386.732-.732L13.863.1z"/>
    </symbol>
    <symbol id="sun-fill" viewBox="0 0 16 16">
        <path d="M8 12a4 4 0 1 0 0-8 4 4 0 0 0 0 8zM8 0a.5.5 0 0 1 .5.5v2a.5.5 0 0 1-1 0v-2A.5.5 0 0 1 8 0zm0 13a.5.5 0 0 1 .5.5v2a.5.5 0 0 1-1 0v-2A.5.5 0 0 1 8 13zm8-5a.5.5 0 0 1-.5.5h-2a.5.5 0 0 1 0-1h2a.5.5 0 0 1 .5.5zM3 8a.5.5 0 0 1-.5.5h-2a.5.5 0 0 1 0-1h2A.5.5 0 0 1 3 8zm10.657-5.657a.5.5 0 0 1 0 .707l-1.414 1.415a.5.5 0 1 1-.707-.708l1.414-1.414a.5.5 0 0 1 .707 0zm-9.193 9.193a.5.5 0 0 1 0 .707L3.05 13.657a.5.5 0 0 1-.707-.707l1.414-1.414a.5.5 0 0 1 .707 0zm9.193 2.121a.5.5 0 0 1-.707 0l-1.414-1.414a.5.5 0 0 1 .707-.707l1.414 1.414a.5.5 0 0 1 0 .707zM4.464 4.465a.5.5 0 0 1-.707 0L2.343 3.05a.5.5 0 1 1 .707-.707l1.414 1.414a.5.5 0 0 1 0 .708z"/>
    </symbol>
</svg>

<div class="dropdown position-fixed bottom-0 end-0 mb-3 me-3 bd-mode-toggle">
    <button class="btn btn-bd-primary py-2 dropdown-toggle d-flex align-items-center"
            id="bd-theme"
            type="button"
            aria-expanded="false"
            data-bs-toggle="dropdown"
            aria-label="Toggle theme (auto)">
        <svg class="bi my-1 theme-icon-active" width="1em" height="1em">
            <use href="#circle-half"></use>
        </svg>
        <span class="visually-hidden" id="bd-theme-text">Toggle theme</span>
    </button>
    <ul class="dropdown-menu dropdown-menu-end shadow" aria-labelledby="bd-theme-text">
        <li>
            <button type="button" class="dropdown-item d-flex align-items-center" data-bs-theme-value="light"
                    aria-pressed="false">
                <svg class="bi me-2 opacity-50 theme-icon" width="1em" height="1em">
                    <use href="#sun-fill"></use>
                </svg>
                Light
                <svg class="bi ms-auto d-none" width="1em" height="1em">
                    <use href="#check2"></use>
                </svg>
            </button>
        </li>
        <li>
            <button type="button" class="dropdown-item d-flex align-items-center" data-bs-theme-value="dark"
                    aria-pressed="false">
                <svg class="bi me-2 opacity-50 theme-icon" width="1em" height="1em">
                    <use href="#moon-stars-fill"></use>
                </svg>
                Dark
                <svg class="bi ms-auto d-none" width="1em" height="1em">
                    <use href="#check2"></use>
                </svg>
            </button>
        </li>
        <li>
            <button type="button" class="dropdown-item d-flex align-items-center active" data-bs-theme-value="auto"
                    aria-pressed="true">
                <svg class="bi me-2 opacity-50 theme-icon" width="1em" height="1em">
                    <use href="#circle-half"></use>
                </svg>
                Auto
                <svg class="bi ms-auto d-none" width="1em" height="1em">
                    <use href="#check2"></use>
                </svg>
            </button>
        </li>
    </ul>
</div>


<header data-bs-theme="dark">
    <div class="collapse text-bg-dark" id="navbarHeader">
        <div class="container">
            <div class="row">
                <div class="col-sm-8 col-md-7 py-4">
                    <h4>Добро пожаловать в наш интернет-магазин!</h4>
                    <p class="text-body-secondary">Мы рады приветствовать вас на нашей виртуальной витрине, где вы
                        найдете широкий ассортимент качественных товаров по доступным ценам. Наша цель - сделать ваше
                        онлайн-пребывание в нашем магазине приятным и удобным. Спасибо, что выбрали нас!</p>
                </div>
                <div class="col-sm-4 offset-md-1 py-4">
                    <h4>Меню</h4>
                    <ul class="list-unstyled">
                        <li><a href="{% url 'product:index' %}" class="text-white">Главная</a></li>
                        <li><a href="{% url 'materials:material_list' %}" class="text-white">Материалы</a></li>
                        <li><a href="{% url 'product:contacts' %}" class="text-white">Контакты</a></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
    <div class="navbar navbar-dark bg-dark shadow-sm">
        <div class="container">
            <a href="{% url 'product:index' %}" class="navbar-brand d-flex align-items-center">
                <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="none" stroke="currentColor"
                     stroke-linecap="round" stroke-linejoin="round" stroke-width="2" aria-hidden="true" class="me-2"
                     viewBox="0 0 24 24">
                    <path d="M23 19a2 2 0 0 1-2 2H3a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h4l2-3h6l2 3h4a2 2 0 0 1 2 2z"/>
                    <circle cx="12" cy="13" r="4"/>
                </svg>
                <strong>ShopOnline</strong>
            </a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarHeader"
                    aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
        </div>
    </div>
</header>

<main>

    {% block content %}
    {% endblock %}

</main>

<footer class="text-body-secondary py-5">
    <div class="container">
        <p class="float-end mb-1">
            <a href="#">Наверх</a>
        </p>
        <p class="mb-1">&copy; 2023-{% now 'Y' %}</p>
    </div>
</footer>
<script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>

</body>
</html>

product/templates/product/contacts.html
{% extends 'product/base.html' %}
{% load crispy_forms_tags %}
{% load crispy_forms_filters %}

{% block content %}

    <section class="py-2 text-center container">
        <div class="row py-lg-5">
            <div class="col-lg-6 col-md-8 mx-auto">
                <h3 class="fw-light">Свяжитесь с нами, если у вас есть вопросы или нужна помощь</h3>
            </div>
        </div>
    </section>

    <div class="album py-5 bg-body-tertiary">
        <div class="container">
            <div class="row">
                <div class="col-md-6">
                    <div class="card">
                        <div class="card-header">
                            <br>
                            <h4>Наши контакты:</h4>
                            <br>
                        </div>
                        <div class="card-body">
                            <h5 class="card-title"></h5>
                            <p class="card-text">
                            <ul>
                                <br>
                                <li>Телефон: +1-555-123-4567</li>
                                <br>
                                <li>Email: info@example.com</li>
                                <br>
                                <li>Адрес: ул. Примерная, 123</li>
                                <br>
                            </ul>
                        </div>
                    </div>
                </div>
                <div class="col-md-6">
                    <form method="post" novalidate class="my-custom-form">
                        {% csrf_token %}
                        {{ form|crispy }}
                        <button type="submit" class="btn btn-outline-secondary form-control">Отправить
                        </button>
                    </form>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

product/templates/product/product_confirm_delete.html
{% extends 'product/base.html' %}

{% block content %}
    <section class="py-2 text-center container">
        <div class="row py-lg-5">
            <div class="col-lg-6 col-md-8 mx-auto">
                <h4>Удаление материала</h4>
            </div>
        </div>
    </section>
    <div class="album py-5 bg-body-tertiary">
        <div class="container">
            <div class="row">
                <div class="col-6">
                    <div class="card">
                        <div class="card">
                            <form method="post">
                                {% csrf_token %}
                                <div class="card-header">
                                    <h6>Хотите удалить продукт "{{ object.title }}"</h6>
                                </div>
                                <div class="card-body">
                                    <button type="submit" class="btn btn-outline-danger">Подтвердить</button>
                                    <a href="{% url 'product:index' %}" class="btn btn-outline-warning">
                                        Отменить</a>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

product/templates/product/product_detail.html
{% extends 'product/base.html' %}

{% block content %}

    <section class="py-5 text-center container">
        <div class="row py-lg-5">
            <div class="col-lg-6 col-md-8 mx-auto">
                <h3 class="fw-light">Описание продукта</h3>
            </div>
        </div>
    </section>

    <div class="album py-5 bg-body-tertiary">
        <div class="container">

            <div class="row">
                <div class="col-6 d-flex flex-column align-items-center">
                    <div style="margin-bottom: auto;">
                        <img src="{{ object.image.url }}"
                             style="width: 200px; height: 250px;" alt="{{ object.title }}">
                    </div>
                    <div class="mt-5 text-center">
                        <a href="{% url 'product:index' %}" class="btn btn-outline-secondary">Вернуться</a>
                        <a href="{% url 'product:edit' object.pk %}" class="btn btn-outline-warning">Редактировать</a>
                        <a href="{% url 'product:delete' object.pk %}" class="btn btn-outline-danger">Удалить</a>
                    </div>
                </div>
                <div class="col-6">
                    <h4>{{ object.title }}</h4><br>
                    <p>{{ object.description }}</p>
                </div>
            </div>
        </div>
    </div>


{% endblock %}

product/templates/product/product_form.html
{% extends 'product/base.html' %}
{% load crispy_forms_tags %}
{% load crispy_forms_filters %}

{% block content %}
    <section class="py-2 text-center container">
        <div class="row py-lg-5">
            <div class="col-lg-6 col-md-8 mx-auto">
                <h3 class="fw-light">
                    {% if object %}
                        Редактирование продукта
                    {% else %}
                        Создание нового продукта
                    {% endif %}
                </h3>
            </div>
        </div>
    </section>

    <div class="album py-5 bg-body-tertiary">
        <div class="container">
            <form method="post" enctype="multipart/form-data" novalidate class="my-custom-form">
                <div class="row">
                    <div class="col-md-6">
                        {% if object %}
                            <h3 class="card-title">
                                Редоктирование продукта
                            </h3>
                            <br>
                        {% else %}
                            <h3 class="card-title">
                                Создание продукта
                            </h3>
                            <br>
                        {% endif %}
                        {% csrf_token %}
                        {{ form|crispy }}
                        <button type="submit" class="btn btn-outline-secondary form-control">
                            {% if object %}
                                Сохранить
                            {% else %}
                                Создать
                            {% endif %}
                        </button>
                    </div>
                    <div class="col-md-6">
                        <h3 class="card-title">
                            Версия продукта
                        </h3>
                        <br>
                        <div class="card-body">
                            {{ formset.management_form }}
                            {% for form in formset.forms %}
                                {{ form|crispy }}
                                {% if not formloop.last %}
                                    <hr>
                                {% endif %}
                            {% endfor %}
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
{% endblock %}

product/templates/product/product_list.html
{% extends 'product/base.html' %}

{% block content %}

    <section class="py-3 text-center container">
        <div class="row py-lg-5">
            <div class="col-lg-6 col-md-8 mx-auto">
                <h1 class="fw-light">Онлайн витрина</h1>
                <p class="lead text-body-secondary">Здесь Вы можете выбрать интересующий Вас продукт. Приятных
                    покупок</p>
            </div>
        </div>
    </section>

    <div class="album py-5 bg-body-tertiary">
        <div class="container">

            <div class="row">
                {% for object in object_list %}
                    <div class="col-4 text-center py-3">
                        <div class="text-center">
                            <img src="{{ object.image.url }}" class="mx-auto"
                                 style="width: 120px; height: 150px;" alt="{{ object.title }}">
                        </div>
                        <div class="card-body py-4">
                            <h5 class="card-title">{{ object.title }}</h5>
                        </div>
                        <div class="card-body py-2">
                            <p class="card-text">{{ object.description|truncatechars:65 }}</p>
                        </div>
                        <ul class="list-group list-group-flush">
                            <li class="list-group-item">Стоимость: {{ object.price }} &#8381;</li>
                            <li class="list-group-item">{% if object.active %}
                                Есть в наличии

                                {% for pk, active in active_versions.items %}
                                    {% if object.pk == pk %}
                                        <li class="list-group-item">
                                            <p>Активная версия: {{ active|title }}</p>
                                        </li>
                                    {% endif %}
                                {% endfor %}


                            {% else %}
                                Нет в наличии
                                <li class="list-group-item"> Нет активной версии</li>
                                </li>
                            {% endif %}
                        </ul>

                        <div class="card-body mt-3">
                            <a href="{% url 'product:view' object.pk %}" class="btn btn-outline-secondary">Подробнее</a>
                        </div>
                    </div>
                {% endfor %}
            </div>
            <div class="container py-5">
                <div class="row">
                    <div class="col-4"></div>
                    <div class="col-4 text-center">
                        <a href="{% url 'product:create' %}" class="btn btn-outline-secondary ">Добавить продукт</a>
                    </div>
                </div>
            </div>
        </div>
    </div>


{% endblock %}